### PR TITLE
Fixes for rbac header, sub list, and dash file move

### PR DESCRIPTION
**Pull request by mstair**
Various minor fixes for when passing args including --azure-only and --subscription

### CODE REVIEW

**Comment by legra-ms** [comment]
In what situations are you seeing a signed session not have the Authorization header after successfully authentically to ARM?

**Comment by mstair** [comment]
Running this command does not populate Auth header:

`stormspotter --service-principal -u user -p pass --tenant tenant --subscription sub --azure-only`

**Comment by legra-ms** [comment]
@mstair  Thanks for the PR. I'll accept and merge once the CLA has been signed.

**Comment by mstair** [comment]
Thanks @legra-ms, I am waiting on approval from my employer to sign. I will get status.

**Pull request closed without merging**
